#include "button.h"

void PressToSos(){
  if(PINC_PINC6==0){
     Point(&PORTC,PIN7);
     Point(&PORTC,PIN7);
     Point(&PORTC,PIN7);
     Line(&PORTC,PIN7);
     Line(&PORTC,PIN7);
     Line(&PORTC,PIN7);
     Point(&PORTC,PIN7);
     Point(&PORTC,PIN7);
     Point(&PORTC,PIN7);
     delay(5);
  }
  }
void SosStop(){
   if(PINC_PINC6==0){
     delay(2);
     while(1){
       if(PINC_PINC6==0){
         delay(2);
         break;}
     Point(&PORTC,PIN7);
     if(PINC_PINC6==0){
       delay(2);
       break;}
     Point(&PORTC,PIN7);
     if(PINC_PINC6==0){
         delay(2);
         break;}
     Point(&PORTC,PIN7);
    if(PINC_PINC6==0){
         delay(2);
         break;}
     Line(&PORTC,PIN7);
     if(PINC_PINC6==0){
         delay(2);
         break;}
     Line(&PORTC,PIN7);
     if(PINC_PINC6==0)
         break;
     Line(&PORTC,PIN7);
     if(PINC_PINC6==0){
         delay(2);
         break;}
     Point(&PORTC,PIN7);
     if(PINC_PINC6==0){
         delay(2);
         break;}
     Point(&PORTC,PIN7);
    if(PINC_PINC6==0){
         delay(2);
         break;}
     Point(&PORTC,PIN7);
     
     }
   }
}