var searchData=
[
  ['s_20main_20application_0',['Objective 3: Building a Control Panel - Internship&apos;s main application',['../md_docs_2work-instructions_2week2-goal1.html#autotoc_md75',1,'']]],
  ['s_20o_20s_20polling_20technique_1',['Objective 6: Architecting S.O.S. - polling technique',['../md_docs_2work-instructions_2week1-goal2.html#autotoc_md68',1,'']]],
  ['s_20polling_20technique_2',['Objective 6: Architecting S.O.S. - polling technique',['../md_docs_2work-instructions_2week1-goal2.html#autotoc_md68',1,'']]],
  ['scheduler_3',['Objective 1: Building from scratch a TASK SCHEDULER',['../md_docs_2work-instructions_2week3-goal1.html#autotoc_md95',1,'']]],
  ['scheduler_4',['Objective 3: Understanding DEBOUNCE with Task Scheduler',['../md_docs_2work-instructions_2week3-goal1.html#autotoc_md99',1,'']]],
  ['schematics_20to_20what_20pins_20you_20can_20output_20a_20pwm_20signal_20and_20if_20those_20pins_20have_20leds_20connected_20not_20all_20pins_20can_20support_20output_20pwm_20signals_5',['622 — CORE — Check on the boards (user guides, schematics) to what pins you can output a PWM signal and if those pins have LEDs connected !!! Not all pins can support/output PWM signals.',['../md__raspunsuri_2622_2_raspuns.html',1,'']]],
  ['scheme_6',['Exercise number scheme',['../md_docs_2work-instructions_2index.html#autotoc_md38',1,'']]],
  ['scratch_20a_20task_20scheduler_7',['Objective 1: Building from scratch a TASK SCHEDULER',['../md_docs_2work-instructions_2week3-goal1.html#autotoc_md95',1,'']]],
  ['sensor_8',['Objective 4: Light sensor',['../md_docs_2work-instructions_2week2-goal1.html#autotoc_md77',1,'']]],
  ['serial_20communication_9',['Objective 1: Understanding Serial Communication',['../md_docs_2work-instructions_2week3-goal3.html#autotoc_md121',1,'']]],
  ['setting_20up_20the_20usart_10',['Objective 2: Setting up the USART',['../md_docs_2work-instructions_2week3-goal3.html#autotoc_md123',1,'']]],
  ['setup_20checklist_11',['8) Initial setup checklist',['../md_docs_2guide_2github-workflow-progress.html#autotoc_md12',1,'']]],
  ['setup_20iar_20embedded_20workbench_20avr_12',['Setup IAR Embedded Workbench (AVR)',['../md_docs_2guide_2setup-iar.html',1,'']]],
  ['should_20read_13',['Great Books Every Engineer Should Read',['../md_docs_2reference-documents_2gbeesr_2index.html',1,'']]],
  ['signal_20and_20if_20those_20pins_20have_20leds_20connected_20not_20all_20pins_20can_20support_20output_20pwm_20signals_14',['622 — CORE — Check on the boards (user guides, schematics) to what pins you can output a PWM signal and if those pins have LEDs connected !!! Not all pins can support/output PWM signals.',['../md__raspunsuri_2622_2_raspuns.html',1,'']]],
  ['signal_20pc7_15',['1.3 Connect LED0 signal (PC7)',['../md_docs_2guide_2logic-analyzer.html#autotoc_md17',1,'']]],
  ['signals_16',['signals',['../md__raspunsuri_2622_2_raspuns.html',1,'622 — CORE — Check on the boards (user guides, schematics) to what pins you can output a PWM signal and if those pins have LEDs connected !!! Not all pins can support/output PWM signals.'],['../md_docs_2work-instructions_2week3-goal2.html#autotoc_md104',1,'Objective 1: Understanding PWM signals']]],
  ['simple_20—_20normal_20mode_20of_20operation_20for_20tc0_17',['Objective 2: Start simple — NORMAL MODE of operation for TC0',['../md_docs_2work-instructions_2week2-goal2.html#autotoc_md86',1,'']]],
  ['size_18',['Objective 5: Measuring the code size',['../md_docs_2work-instructions_2week3-goal2.html#autotoc_md112',1,'']]],
  ['sm_19',['Objective 6: Understanding State Machines (SM)',['../md_docs_2work-instructions_2week3-goal2.html#autotoc_md114',1,'']]],
  ['software_20',['2. PulseView software',['../md_docs_2guide_2logic-analyzer.html#autotoc_md18',1,'']]],
  ['start_20simple_20—_20normal_20mode_20of_20operation_20for_20tc0_21',['Objective 2: Start simple — NORMAL MODE of operation for TC0',['../md_docs_2work-instructions_2week2-goal2.html#autotoc_md86',1,'']]],
  ['started_22',['Getting Started',['../md_docs_2guide_2getting-started.html',1,'']]],
  ['state_20machines_23',['Objective 7: Implementing State Machines',['../md_docs_2work-instructions_2week3-goal2.html#autotoc_md116',1,'']]],
  ['state_20machines_20sm_24',['Objective 6: Understanding State Machines (SM)',['../md_docs_2work-instructions_2week3-goal2.html#autotoc_md114',1,'']]],
  ['student_20and_20mentor_20usage_25',['7) Student and mentor usage',['../md_docs_2guide_2github-workflow-progress.html#autotoc_md11',1,'']]],
  ['student_20branch_26',['3) Branch model inside each student branch',['../md_docs_2guide_2github-workflow-progress.html#autotoc_md7',1,'']]],
  ['student_20branch_20model_27',['2) Student branch model',['../md_docs_2guide_2github-workflow-progress.html#autotoc_md6',1,'']]],
  ['students_28',['1) Keep &lt;span class=&quot;tt&quot;&gt;main&lt;/span&gt; untouchable by students',['../md_docs_2guide_2github-workflow-progress.html#autotoc_md5',1,'']]],
  ['summer_20internship_20documentation_29',['Summer Internship documentation',['../md_docs_2index.html',1,'']]],
  ['support_20output_20pwm_20signals_30',['622 — CORE — Check on the boards (user guides, schematics) to what pins you can output a PWM signal and if those pins have LEDs connected !!! Not all pins can support/output PWM signals.',['../md__raspunsuri_2622_2_raspuns.html',1,'']]],
  ['sw0_20debounce_31',['Objective 5: Reading the user button SW0 - debounce',['../md_docs_2work-instructions_2week1-goal2.html#autotoc_md66',1,'']]]
];
