var searchData=
[
  ['panel_20application_20again_20as_20a_20masterpiece_0',['Objective 4: Control Panel Application ... AGAIN ?! ... as a masterpiece ;)',['../md_docs_2work-instructions_2week3-goal3.html#autotoc_md127',1,'']]],
  ['panel_20application_20re_20revisited_1',['Objective 8: Control Panel Application RE-REVISITED',['../md_docs_2work-instructions_2week3-goal2.html#autotoc_md118',1,'']]],
  ['panel_20internship_20s_20main_20application_2',['Objective 3: Building a Control Panel - Internship&apos;s main application',['../md_docs_2work-instructions_2week2-goal1.html#autotoc_md75',1,'']]],
  ['panel_20revisited_3',['Objective 4: Control Panel REVISITED',['../md_docs_2work-instructions_2week3-goal1.html#autotoc_md101',1,'']]],
  ['parsing_4',['5) One PR per tracked goal (instead of commit message parsing)',['../md_docs_2guide_2github-workflow-progress.html#autotoc_md9',1,'']]],
  ['pc7_5',['1.3 Connect LED0 signal (PC7)',['../md_docs_2guide_2logic-analyzer.html#autotoc_md17',1,'']]],
  ['per_20tracked_20goal_20instead_20of_20commit_20message_20parsing_6',['5) One PR per tracked goal (instead of commit message parsing)',['../md_docs_2guide_2github-workflow-progress.html#autotoc_md9',1,'']]],
  ['pins_20can_20support_20output_20pwm_20signals_7',['622 — CORE — Check on the boards (user guides, schematics) to what pins you can output a PWM signal and if those pins have LEDs connected !!! Not all pins can support/output PWM signals.',['../md__raspunsuri_2622_2_raspuns.html',1,'']]],
  ['pins_20have_20leds_20connected_20not_20all_20pins_20can_20support_20output_20pwm_20signals_8',['622 — CORE — Check on the boards (user guides, schematics) to what pins you can output a PWM signal and if those pins have LEDs connected !!! Not all pins can support/output PWM signals.',['../md__raspunsuri_2622_2_raspuns.html',1,'']]],
  ['pins_20you_20can_20output_20a_20pwm_20signal_20and_20if_20those_20pins_20have_20leds_20connected_20not_20all_20pins_20can_20support_20output_20pwm_20signals_9',['622 — CORE — Check on the boards (user guides, schematics) to what pins you can output a PWM signal and if those pins have LEDs connected !!! Not all pins can support/output PWM signals.',['../md__raspunsuri_2622_2_raspuns.html',1,'']]],
  ['polling_20technique_10',['Objective 6: Architecting S.O.S. - polling technique',['../md_docs_2work-instructions_2week1-goal2.html#autotoc_md68',1,'']]],
  ['pr_20per_20tracked_20goal_20instead_20of_20commit_20message_20parsing_11',['5) One PR per tracked goal (instead of commit message parsing)',['../md_docs_2guide_2github-workflow-progress.html#autotoc_md9',1,'']]],
  ['principle_12',['Objective 3: GPIO and Generalization Principle',['../md_docs_2work-instructions_2week1-goal2.html#autotoc_md62',1,'']]],
  ['prize_13',['End of Internship Prize',['../md_docs_2quiz_2results.html#autotoc_md34',1,'']]],
  ['programming_14',['Objective 4: Modular programming',['../md_docs_2work-instructions_2week1-goal2.html#autotoc_md64',1,'']]],
  ['programming_20language_20know_20how_15',['Objective 5: Refresh your C programming language know-how',['../md_docs_2work-instructions_2week1-goal1.html#autotoc_md51',1,'']]],
  ['progress_16',['Check your work progress',['../md_docs_2work-instructions_2progress.html',1,'']]],
  ['progress_20dashboard_20in_20github_17',['6) Automatic progress dashboard in GitHub',['../md_docs_2guide_2github-workflow-progress.html#autotoc_md10',1,'']]],
  ['progress_20tracking_18',['GitHub Workflow and Progress Tracking',['../md_docs_2guide_2github-workflow-progress.html',1,'']]],
  ['project_19',['Create a new AVR project',['../md_docs_2guide_2new-project-iar.html#autotoc_md20',1,'']]],
  ['project_20tutorial_20with_20iar_20',['New Project Tutorial with IAR',['../md_docs_2guide_2new-project-iar.html',1,'']]],
  ['project_20with_20iar_20embedded_20workbench_20ide_21',['Objective 4: Build a new project with IAR Embedded Workbench IDE',['../md_docs_2work-instructions_2week1-goal1.html#autotoc_md49',1,'']]],
  ['pulseview_20software_22',['2. PulseView software',['../md_docs_2guide_2logic-analyzer.html#autotoc_md18',1,'']]],
  ['pwm_20mode_20of_20operation_20for_20tc0_23',['Objective 2: Fast PWM MODE of operation for TC0',['../md_docs_2work-instructions_2week3-goal2.html#autotoc_md106',1,'']]],
  ['pwm_20signal_20and_20if_20those_20pins_20have_20leds_20connected_20not_20all_20pins_20can_20support_20output_20pwm_20signals_24',['622 — CORE — Check on the boards (user guides, schematics) to what pins you can output a PWM signal and if those pins have LEDs connected !!! Not all pins can support/output PWM signals.',['../md__raspunsuri_2622_2_raspuns.html',1,'']]],
  ['pwm_20signals_25',['PWM signals',['../md__raspunsuri_2622_2_raspuns.html',1,'622 — CORE — Check on the boards (user guides, schematics) to what pins you can output a PWM signal and if those pins have LEDs connected !!! Not all pins can support/output PWM signals.'],['../md_docs_2work-instructions_2week3-goal2.html#autotoc_md104',1,'Objective 1: Understanding PWM signals']]]
];
