var searchData=
[
  ['a_20control_20panel_20internship_20s_20main_20application_0',['Objective 3: Building a Control Panel - Internship&apos;s main application',['../md_docs_2work-instructions_2week2-goal1.html#autotoc_md75',1,'']]],
  ['a_20masterpiece_1',['Objective 4: Control Panel Application ... AGAIN ?! ... as a masterpiece ;)',['../md_docs_2work-instructions_2week3-goal3.html#autotoc_md127',1,'']]],
  ['a_20new_20avr_20project_2',['Create a new AVR project',['../md_docs_2guide_2new-project-iar.html#autotoc_md20',1,'']]],
  ['a_20new_20project_20with_20iar_20embedded_20workbench_20ide_3',['Objective 4: Build a new project with IAR Embedded Workbench IDE',['../md_docs_2work-instructions_2week1-goal1.html#autotoc_md49',1,'']]],
  ['a_20pwm_20signal_20and_20if_20those_20pins_20have_20leds_20connected_20not_20all_20pins_20can_20support_20output_20pwm_20signals_4',['622 — CORE — Check on the boards (user guides, schematics) to what pins you can output a PWM signal and if those pins have LEDs connected !!! Not all pins can support/output PWM signals.',['../md__raspunsuri_2622_2_raspuns.html',1,'']]],
  ['a_20task_20scheduler_5',['Objective 1: Building from scratch a TASK SCHEDULER',['../md_docs_2work-instructions_2week3-goal1.html#autotoc_md95',1,'']]],
  ['adc_6',['Objective 5: Mastering the ADC',['../md_docs_2work-instructions_2week2-goal1.html#autotoc_md79',1,'']]],
  ['advancing_20tc1_7',['Objective 5: Advancing TC1',['../md_docs_2work-instructions_2week2-goal2.html#autotoc_md92',1,'']]],
  ['again_20as_20a_20masterpiece_8',['Objective 4: Control Panel Application ... AGAIN ?! ... as a masterpiece ;)',['../md_docs_2work-instructions_2week3-goal3.html#autotoc_md127',1,'']]],
  ['all_20pins_20can_20support_20output_20pwm_20signals_9',['622 — CORE — Check on the boards (user guides, schematics) to what pins you can output a PWM signal and if those pins have LEDs connected !!! Not all pins can support/output PWM signals.',['../md__raspunsuri_2622_2_raspuns.html',1,'']]],
  ['ambient_20light_20application_10',['Objective 6: Ambient Light Application',['../md_docs_2work-instructions_2week2-goal1.html#autotoc_md81',1,'']]],
  ['ambient_20light_20application_20revisited_11',['Objective 2: Ambient Light Application REVISITED',['../md_docs_2work-instructions_2week3-goal1.html#autotoc_md97',1,'']]],
  ['analyzer_20example_20for_20led0_20exercise_12',['How to work with Logic Analyzer (example for LED0 exercise)',['../md_docs_2guide_2logic-analyzer.html',1,'']]],
  ['and_20generalization_20principle_13',['Objective 3: GPIO and Generalization Principle',['../md_docs_2work-instructions_2week1-goal2.html#autotoc_md62',1,'']]],
  ['and_20if_20those_20pins_20have_20leds_20connected_20not_20all_20pins_20can_20support_20output_20pwm_20signals_14',['622 — CORE — Check on the boards (user guides, schematics) to what pins you can output a PWM signal and if those pins have LEDs connected !!! Not all pins can support/output PWM signals.',['../md__raspunsuri_2622_2_raspuns.html',1,'']]],
  ['and_20mentor_20usage_15',['7) Student and mentor usage',['../md_docs_2guide_2github-workflow-progress.html#autotoc_md11',1,'']]],
  ['and_20progress_20tracking_16',['GitHub Workflow and Progress Tracking',['../md_docs_2guide_2github-workflow-progress.html',1,'']]],
  ['and_20test_20application_17',['Objective 3: Implement driver and test application',['../md_docs_2work-instructions_2week3-goal3.html#autotoc_md125',1,'']]],
  ['application_18',['Objective 6: Ambient Light Application',['../md_docs_2work-instructions_2week2-goal1.html#autotoc_md81',1,'']]],
  ['application_19',['application',['../md_docs_2work-instructions_2week2-goal1.html#autotoc_md75',1,'Objective 3: Building a Control Panel - Internship&apos;s main application'],['../md_docs_2work-instructions_2week3-goal3.html#autotoc_md125',1,'Objective 3: Implement driver and test application']]],
  ['application_20again_20as_20a_20masterpiece_20',['Objective 4: Control Panel Application ... AGAIN ?! ... as a masterpiece ;)',['../md_docs_2work-instructions_2week3-goal3.html#autotoc_md127',1,'']]],
  ['application_20re_20revisited_21',['Objective 8: Control Panel Application RE-REVISITED',['../md_docs_2work-instructions_2week3-goal2.html#autotoc_md118',1,'']]],
  ['application_20revisited_22',['Objective 2: Ambient Light Application REVISITED',['../md_docs_2work-instructions_2week3-goal1.html#autotoc_md97',1,'']]],
  ['architecting_20s_20o_20s_20polling_20technique_23',['Objective 6: Architecting S.O.S. - polling technique',['../md_docs_2work-instructions_2week1-goal2.html#autotoc_md68',1,'']]],
  ['as_20a_20masterpiece_24',['Objective 4: Control Panel Application ... AGAIN ?! ... as a masterpiece ;)',['../md_docs_2work-instructions_2week3-goal3.html#autotoc_md127',1,'']]],
  ['automatic_20progress_20dashboard_20in_20github_25',['6) Automatic progress dashboard in GitHub',['../md_docs_2guide_2github-workflow-progress.html#autotoc_md10',1,'']]],
  ['avr_26',['Setup IAR Embedded Workbench (AVR)',['../md_docs_2guide_2setup-iar.html',1,'']]],
  ['avr_20project_27',['Create a new AVR project',['../md_docs_2guide_2new-project-iar.html#autotoc_md20',1,'']]]
];
